version: '3.9'
name: 'uzor_utum'
services:
  db:
    image: postgres:alpine3.18
    volumes:
      - ./database:/var/lib/postgresql/data
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DATABASE}
    ports:
      - '${DB_PORT}:5432'
    expose:
      - ${DB_PORT}
    healthcheck:
      test:
        [ 'CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DATABASE}' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 6373:8080
