version: '3.9'
name: 'uzor_utum'
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    hostname: rabbitmq
    restart: always
    container_name: rabbitmq
    ports:
      - 9802:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=${LOGIN_RABBIT}
      - RABBITMQ_DEFAULT_PASS=${PASS_RABBIT}
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rmq:/var/lib/rabbitmq
    healthcheck:
      test: [ 'CMD', 'rabbitmqctl', 'status' ]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - .env
