version: '3.9'
name: 'uzor_utum'
services:
  db:
    image: postgres:alpine3.18
    volumes:
      - ./database:/var/lib/postgresql/data
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DATABASE}
    ports:
      - '${DB_PORT}:5432'
    expose:
      - ${DB_PORT}
    healthcheck:
      test:
        [ 'CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DATABASE}' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3.9-management
    hostname: rabbitmq
    restart: always
    container_name: rabbitmq
    ports:
      - 9802:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=${LOGIN_RABBIT}
      - RABBITMQ_DEFAULT_PASS=${PASS_RABBIT}
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: [ 'CMD', 'rabbitmqctl', 'status' ]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - .env
#  api:
#    build: .
#    ports:
#      - '3000:3000'
#    depends_on:
#      - db
#      - rabbitmq
#    volumes:
#      - .:/app
#      - /app/node_modules